# ================================
# Build image
# ================================
FROM swift:5.7-focal as build

LABEL org.opencontainers.description="Development image."
LABEL org.opencontainers.image.license=MIT
LABEL org.opencontainers.image.src=https://github.com/m-housh/swift-manual-s-api

# Install OS updates and, if needed, sqlite3
RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    && apt-get -q update \
    && apt-get -q dist-upgrade -y\
    && apt-get -q install \
      libcurl4 \
    && rm -rf /var/lib/apt/lists/*

# Set up a build area
WORKDIR /app

# Copy entire repo into container
COPY . .

# Build everything
RUN swift build

# Let Docker bind to port 8080
EXPOSE 8080

CMD ["swift", "test"]
