
name: Publish Docker image

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - success
  push:
    branches:
      - "**"
    tags:
      - "*.*.*"
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

permissions:
  contents: write
  id-token: write

jobs:
  docker:
    name: Push Docker image to Github
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            m-housh/swift-manual-s-api
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.event.name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Bootstrap/Dockerfile.prod
          push: ${{ github.event.name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
