# Create a release when a new tag is pushed.
#
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Release Text
        run: echo ${{ steps.get_version.outputs.VERSION }} > Release.txt

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          files: |
            Release.txt
            LICENSE
          token: ${{ secrets.GHCRIO_TOKEN }}

      - name: Build and push image.
        uses: ./.github/workflows/publish-docker-image.yml
        with:
          file: ./Bootstrap/Dockerfile.prod
          push: true
        secrets:
          token: ${{ secrets.GHCRIO_TOKEN }}

